### ISSUE TITLE
Inscription/connexion

### ISSUE THREAD

**Issue by evlm-afk** [Michel-SG/Xtrembook-front#17]
Pour s'inscrire, lorsque je clique sur "Envoyer", il ne se passe rien du tout.
Si je regarde la table `user` de la base de données, mon compte apparaît bien.
Et il y a cette erreur dans la console de mon navigateur : 
`ERROR Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":500,"statusText":"Internal Server Error","url":"http://localhost:3000/api/user/signup","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://localhost:3000/api/user/signup: 500 Internal Server Error","error":{"error":"problème d'insertion dans adresse: TypeError: Cannot read property 'num' of undefined"}}`

Quand j'essaye de me connecter avec l'utilisateur que je viens de créer, ça fonctionne par contre

**Comment by michelsadeu** [comment]
je pense que c'est un problème dans ta base de données
